### ISSUE TITLE
Try implementing/training the SIREN model

### ISSUE THREAD

**Issue by scaenazzo** [lcipolina/escher#9]
https://arxiv.org/abs/2006.09661

**Comment by lcipolina** [comment]
ok, I have made the SIREN code to work ! yay!

Now I'll need some help in how to use it to extrapolate. 

We should schedule a meeting. Maybe over the weekend.

**Comment by lcipolina** [comment]
Basics of SIREN model implemented. 

The corresponding Google Colab is under the ML folder
